name: Second Workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Get dependencies
          run: npm ci
        - name: Lint code
          run: npm run lint
        - name: List content
          run: ls -al
        - name: Run the server 
          run: npm run dev < /dev/null & npx wait-on "http://localhost:5173" --timeout 10s
        - name: Cypress Tests 
          run: npx cypress run
  build: 
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Get dependencies
          uses: actions/cache@v4
          with: 
            path: node_modules
            key: npm-dep-${{ hashFiles('**/package-lock.json') }}
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
        - name: Pseudo Deployement
          run: echo "Deploying App"


    